// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf1qXwNETzeD1bRwGVJXPuE2XB4BwwExw',
    appId: '1:1043739333910:web:db870a33ca2a30a3c7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    authDomain: 'evetick-a2d16.firebaseapp.com',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
    measurementId: 'G-55D7L3PHB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRDXyRPgAinhzrNDV9eTFqQsx-RHtXgQ',
    appId: '1:1043739333910:android:190a8736c3458156c7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOvjSVWRGw994Er5LBgjoC4CkUSouVV0',
    appId: '1:1043739333910:ios:3b2c97fc1d7fd524c7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
    androidClientId: '1043739333910-i79d0p2oaj495170opjo166ajkr7vsib.apps.googleusercontent.com',
    iosClientId: '1043739333910-lh2jjii7j8o4kbkrl9g31bo7u5270k7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.evetick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkOvjSVWRGw994Er5LBgjoC4CkUSouVV0',
    appId: '1:1043739333910:ios:3b2c97fc1d7fd524c7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
    androidClientId: '1043739333910-i79d0p2oaj495170opjo166ajkr7vsib.apps.googleusercontent.com',
    iosClientId: '1043739333910-lh2jjii7j8o4kbkrl9g31bo7u5270k7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.evetick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf1qXwNETzeD1bRwGVJXPuE2XB4BwwExw',
    appId: '1:1043739333910:web:5cbabb5b98ff1c3bc7ac37',
    messagingSenderId: '1043739333910',
    projectId: 'evetick-a2d16',
    authDomain: 'evetick-a2d16.firebaseapp.com',
    storageBucket: 'evetick-a2d16.firebasestorage.app',
    measurementId: 'G-9DLBJ5WPQX',
  );
}
